//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class coursim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coursim()
        {
            this.Notification = new HashSet<Notification>();
            this.StudentInCourse = new HashSet<StudentInCourse>();
            this.TimesOfCourse = new HashSet<TimesOfCourse>();
        }
    
        public int Idcourse { get; set; }
        public int idSubject { get; set; }
        public int IDTeacher { get; set; }
        public string classStart { get; set; }
        public string classEnd { get; set; }
        public int units { get; set; }
        public string Type { get; set; }
        public string Statut { get; set; }
        public string Date { get; set; }
    
        public virtual SubjectOfCoursim SubjectOfCoursim { get; set; }
        public virtual teacher teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentInCourse> StudentInCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesOfCourse> TimesOfCourse { get; set; }
    }
}
