//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilite
    {
        public int IdDisponibilite { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime dateend { get; set; }
        public int IdTeacher { get; set; }
    
        public virtual teacher teacher { get; set; }
    }
}
