//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int IdfeedBack { get; set; }
        public int idStudent { get; set; }
        public int idTeacher { get; set; }
        public string point { get; set; }
        public string remark { get; set; }
    
        public virtual student student { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
