//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SicoumProDBEntities : DbContext
    {
        public SicoumProDBEntities()
            : base("name=SicoumProDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Domain> Domain { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<SubjectOfCoursim> SubjectOfCoursim { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<TimesOfCourse> TimesOfCourse { get; set; }
        public virtual DbSet<TypeCours> TypeCours { get; set; }
        public virtual DbSet<Ville> Ville { get; set; }
        public virtual DbSet<coursim> coursim { get; set; }
        public virtual DbSet<CoursimOfTeacher> CoursimOfTeacher { get; set; }
        public virtual DbSet<StudentInCourse> StudentInCourse { get; set; }
        public virtual DbSet<Disponibilite> Disponibilite { get; set; }
    }
}
