//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int IdNotification { get; set; }
        public string Content { get; set; }
        public string Date { get; set; }
        public string Readed { get; set; }
        public Nullable<int> IdCourse { get; set; }
    
        public virtual coursim coursim { get; set; }
    }
}
