//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInCourse
    {
        public int IdStudentInCourse { get; set; }
        public int idStudent { get; set; }
        public int IdCourse { get; set; }
        public bool Pay { get; set; }
        public bool StatusTeacher { get; set; }
    
        public virtual coursim coursim { get; set; }
        public virtual student student { get; set; }
    }
}
